-- Preserve existing values while allowing future profile fields to distinguish
-- unanswered nulls from explicit empty/false/zero answers.

ALTER TABLE "organizations"
  ALTER COLUMN "legal_entity_name" DROP DEFAULT,
  ALTER COLUMN "legal_entity_name" DROP NOT NULL,
  ALTER COLUMN "website" DROP DEFAULT,
  ALTER COLUMN "website" DROP NOT NULL,
  ALTER COLUMN "contact_email" DROP DEFAULT,
  ALTER COLUMN "contact_email" DROP NOT NULL,
  ALTER COLUMN "security_contact_email" DROP DEFAULT,
  ALTER COLUMN "security_contact_email" DROP NOT NULL,
  ALTER COLUMN "privacy_contact_email" DROP DEFAULT,
  ALTER COLUMN "privacy_contact_email" DROP NOT NULL,
  ALTER COLUMN "country" DROP DEFAULT,
  ALTER COLUMN "country" DROP NOT NULL,
  ALTER COLUMN "address" DROP DEFAULT,
  ALTER COLUMN "address" DROP NOT NULL,
  ALTER COLUMN "employee_count" DROP NOT NULL,
  ALTER COLUMN "handles_pii" DROP NOT NULL,
  ALTER COLUMN "handles_sensitive_data" DROP NOT NULL,
  ALTER COLUMN "industries" TYPE jsonb USING to_jsonb("industries"),
  ALTER COLUMN "regions" TYPE jsonb USING to_jsonb("regions"),
  ALTER COLUMN "compliance_goals" TYPE jsonb USING to_jsonb("compliance_goals");

ALTER TABLE "service_profiles"
  ALTER COLUMN "service_name" DROP DEFAULT,
  ALTER COLUMN "service_name" DROP NOT NULL,
  ALTER COLUMN "service_description" DROP DEFAULT,
  ALTER COLUMN "service_description" DROP NOT NULL,
  ALTER COLUMN "service_url" DROP DEFAULT,
  ALTER COLUMN "service_url" DROP NOT NULL,
  ALTER COLUMN "children_directed" DROP DEFAULT,
  ALTER COLUMN "children_directed" DROP NOT NULL,
  ALTER COLUMN "minimum_user_age" DROP DEFAULT,
  ALTER COLUMN "minimum_user_age" DROP NOT NULL,
  ALTER COLUMN "uses_cookies" DROP DEFAULT,
  ALTER COLUMN "uses_cookies" DROP NOT NULL,
  ALTER COLUMN "primary_hosting_region" DROP DEFAULT,
  ALTER COLUMN "primary_hosting_region" DROP NOT NULL,
  ALTER COLUMN "user_types" DROP DEFAULT,
  ALTER COLUMN "user_types" TYPE jsonb USING to_jsonb("user_types"),
  ALTER COLUMN "customer_types" DROP DEFAULT,
  ALTER COLUMN "customer_types" TYPE jsonb USING to_jsonb("customer_types"),
  ALTER COLUMN "availability_regions" DROP DEFAULT,
  ALTER COLUMN "availability_regions" TYPE jsonb USING to_jsonb("availability_regions"),
  ALTER COLUMN "cookie_types" DROP DEFAULT,
  ALTER COLUMN "cookie_types" TYPE jsonb USING to_jsonb("cookie_types"),
  ALTER COLUMN "data_residency_options" DROP DEFAULT,
  ALTER COLUMN "data_residency_options" TYPE jsonb USING to_jsonb("data_residency_options");

ALTER TABLE "privacy_profiles"
  ALTER COLUMN "response_timeline_days" DROP DEFAULT,
  ALTER COLUMN "response_timeline_days" DROP NOT NULL,
  ALTER COLUMN "identity_verification_required" DROP DEFAULT,
  ALTER COLUMN "identity_verification_required" DROP NOT NULL,
  ALTER COLUMN "authorized_agent_supported" DROP DEFAULT,
  ALTER COLUMN "authorized_agent_supported" DROP NOT NULL,
  ALTER COLUMN "appeal_process_exists" DROP DEFAULT,
  ALTER COLUMN "appeal_process_exists" DROP NOT NULL,
  ALTER COLUMN "cookie_consent_mechanism" DROP DEFAULT,
  ALTER COLUMN "cookie_consent_mechanism" DROP NOT NULL,
  ALTER COLUMN "do_not_track_response" DROP DEFAULT,
  ALTER COLUMN "do_not_track_response" DROP NOT NULL,
  ALTER COLUMN "global_privacy_control_supported" DROP DEFAULT,
  ALTER COLUMN "global_privacy_control_supported" DROP NOT NULL,
  ALTER COLUMN "sends_marketing_emails" DROP DEFAULT,
  ALTER COLUMN "sends_marketing_emails" DROP NOT NULL,
  ALTER COLUMN "marketing_opt_out_method" DROP DEFAULT,
  ALTER COLUMN "marketing_opt_out_method" DROP NOT NULL,
  ALTER COLUMN "transactional_emails_sent" DROP DEFAULT,
  ALTER COLUMN "transactional_emails_sent" DROP NOT NULL,
  ALTER COLUMN "cross_border_transfers" DROP DEFAULT,
  ALTER COLUMN "cross_border_transfers" DROP NOT NULL,
  ALTER COLUMN "sells_or_shares_data" DROP DEFAULT,
  ALTER COLUMN "sells_or_shares_data" DROP NOT NULL,
  ALTER COLUMN "do_not_sell_link" DROP DEFAULT,
  ALTER COLUMN "do_not_sell_link" DROP NOT NULL,
  ALTER COLUMN "dpo_name" DROP DEFAULT,
  ALTER COLUMN "dpo_name" DROP NOT NULL,
  ALTER COLUMN "dpo_email" DROP DEFAULT,
  ALTER COLUMN "dpo_email" DROP NOT NULL,
  ALTER COLUMN "eu_representative_name" DROP DEFAULT,
  ALTER COLUMN "eu_representative_name" DROP NOT NULL,
  ALTER COLUMN "eu_representative_address" DROP DEFAULT,
  ALTER COLUMN "eu_representative_address" DROP NOT NULL,
  ALTER COLUMN "uses_automated_decision_making" DROP DEFAULT,
  ALTER COLUMN "uses_automated_decision_making" DROP NOT NULL,
  ALTER COLUMN "supported_rights" DROP DEFAULT,
  ALTER COLUMN "supported_rights" TYPE jsonb USING to_jsonb("supported_rights"),
  ALTER COLUMN "request_methods" DROP DEFAULT,
  ALTER COLUMN "request_methods" TYPE jsonb USING to_jsonb("request_methods"),
  ALTER COLUMN "transfer_mechanisms" DROP DEFAULT,
  ALTER COLUMN "transfer_mechanisms" TYPE jsonb USING to_jsonb("transfer_mechanisms");

ALTER TABLE "infrastructure_profiles"
  ALTER COLUMN "mfa_enabled" DROP NOT NULL,
  ALTER COLUMN "encrypted_devices_required" DROP NOT NULL,
  ALTER COLUMN "backups_enabled" DROP NOT NULL,
  ALTER COLUMN "centralized_logging_enabled" DROP NOT NULL,
  ALTER COLUMN "at_rest_algorithm" DROP DEFAULT,
  ALTER COLUMN "at_rest_algorithm" DROP NOT NULL,
  ALTER COLUMN "in_transit_minimum_tls_version" DROP DEFAULT,
  ALTER COLUMN "in_transit_minimum_tls_version" DROP NOT NULL,
  ALTER COLUMN "key_management_provider" DROP DEFAULT,
  ALTER COLUMN "key_management_provider" DROP NOT NULL,
  ALTER COLUMN "log_retention_days" DROP DEFAULT,
  ALTER COLUMN "log_retention_days" DROP NOT NULL,
  ALTER COLUMN "security_monitoring_owner" DROP DEFAULT,
  ALTER COLUMN "security_monitoring_owner" DROP NOT NULL,
  ALTER COLUMN "scanning_cadence" DROP DEFAULT,
  ALTER COLUMN "scanning_cadence" DROP NOT NULL,
  ALTER COLUMN "patching_sla_critical_days" DROP DEFAULT,
  ALTER COLUMN "patching_sla_critical_days" DROP NOT NULL,
  ALTER COLUMN "patching_sla_high_days" DROP DEFAULT,
  ALTER COLUMN "patching_sla_high_days" DROP NOT NULL,
  ALTER COLUMN "incident_response_plan_exists" DROP DEFAULT,
  ALTER COLUMN "incident_response_plan_exists" DROP NOT NULL,
  ALTER COLUMN "incident_notification_timeline" DROP DEFAULT,
  ALTER COLUMN "incident_notification_timeline" DROP NOT NULL,
  ALTER COLUMN "customer_notification_process" DROP DEFAULT,
  ALTER COLUMN "customer_notification_process" DROP NOT NULL,
  ALTER COLUMN "incident_response_last_tested_date" DROP DEFAULT,
  ALTER COLUMN "incident_response_last_tested_date" DROP NOT NULL,
  ALTER COLUMN "backup_cadence" DROP DEFAULT,
  ALTER COLUMN "backup_cadence" DROP NOT NULL,
  ALTER COLUMN "backup_retention_days" DROP DEFAULT,
  ALTER COLUMN "backup_retention_days" DROP NOT NULL,
  ALTER COLUMN "restore_testing_cadence" DROP DEFAULT,
  ALTER COLUMN "restore_testing_cadence" DROP NOT NULL,
  ALTER COLUMN "vendor_review_required" DROP DEFAULT,
  ALTER COLUMN "vendor_review_required" DROP NOT NULL,
  ALTER COLUMN "vendor_review_cadence" DROP DEFAULT,
  ALTER COLUMN "vendor_review_cadence" DROP NOT NULL,
  ALTER COLUMN "dpa_required_for_processors" DROP DEFAULT,
  ALTER COLUMN "dpa_required_for_processors" DROP NOT NULL;

ALTER TABLE "data_handling_profiles"
  ALTER COLUMN "stores_pii" DROP NOT NULL,
  ALTER COLUMN "stores_healthcare_data" DROP NOT NULL,
  ALTER COLUMN "encryption_at_rest" DROP NOT NULL,
  ALTER COLUMN "encryption_in_transit" DROP NOT NULL,
  ALTER COLUMN "production_data_in_development" DROP NOT NULL,
  ALTER COLUMN "retention_policy_exists" DROP NOT NULL;

ALTER TABLE "organization_data_types"
  ALTER COLUMN "description" DROP NOT NULL,
  ALTER COLUMN "is_sensitive" DROP NOT NULL,
  ALTER COLUMN "is_required" DROP DEFAULT,
  ALTER COLUMN "is_required" DROP NOT NULL,
  ALTER COLUMN "subject_types" DROP DEFAULT,
  ALTER COLUMN "subject_types" TYPE jsonb USING to_jsonb("subject_types"),
  ALTER COLUMN "collection_methods" DROP DEFAULT,
  ALTER COLUMN "collection_methods" TYPE jsonb USING to_jsonb("collection_methods");

ALTER TABLE "access_profiles"
  ALTER COLUMN "mfa_required" DROP NOT NULL,
  ALTER COLUMN "sso_enabled" DROP NOT NULL,
  ALTER COLUMN "shared_accounts_exist" DROP NOT NULL,
  ALTER COLUMN "offboarding_process_exists" DROP NOT NULL,
  ALTER COLUMN "access_reviews_performed" DROP NOT NULL,
  ALTER COLUMN "privileged_access_restricted" DROP NOT NULL,
  ALTER COLUMN "least_privilege" DROP DEFAULT,
  ALTER COLUMN "least_privilege" DROP NOT NULL,
  ALTER COLUMN "role_based_access" DROP DEFAULT,
  ALTER COLUMN "role_based_access" DROP NOT NULL,
  ALTER COLUMN "access_review_cadence" DROP DEFAULT,
  ALTER COLUMN "access_review_cadence" DROP NOT NULL,
  ALTER COLUMN "admin_approval_required" DROP DEFAULT,
  ALTER COLUMN "admin_approval_required" DROP NOT NULL,
  ALTER COLUMN "password_manager_required" DROP DEFAULT,
  ALTER COLUMN "password_manager_required" DROP NOT NULL;
