export const POSTHOG_EVENTS = {
  USER_SIGNED_IN: "user_signed_in",
  MAGIC_LINK_SENT: "magic_link_sent",
  ORGANIZATION_CREATED: "organization_created",
  ONBOARDING_COMPLIANCE_GOALS_SELECTED: "onboarding_compliance_goals_selected",
  COMPANY_PROFILE_SAVED: "company_profile_saved",
  PRIVACY_PROFILE_SAVED: "privacy_profile_saved",
  INFRASTRUCTURE_PROFILE_SAVED: "infrastructure_profile_saved",
  SECURITY_PROFILE_SAVED: "security_profile_saved",
  ACCESS_PROFILE_SAVED: "access_profile_saved",
  VENDOR_ADDED_FROM_CATALOG: "vendor_added_from_catalog",
  VENDOR_ADDED_MANUALLY: "vendor_added_manually",
  VENDOR_UPDATED: "vendor_updated",
  VENDOR_DELETED: "vendor_deleted",
  SERVICE_CREATED: "service_created",
  SERVICE_UPDATED: "service_updated",
  SERVICE_DELETED: "service_deleted",
  SERVICE_REORDERED: "service_reordered",
  DATA_TYPE_CREATED: "data_type_created",
  DATA_TYPE_UPDATED: "data_type_updated",
  DATA_TYPE_DELETED: "data_type_deleted",
  DATA_TYPE_REORDERED: "data_type_reordered",
  ACTIVITY_CREATED: "activity_created",
  ACTIVITY_UPDATED: "activity_updated",
  ACTIVITY_DELETED: "activity_deleted",
  ACTIVITY_REORDERED: "activity_reordered",
  SERVICE_PROVIDER_USAGE_CREATED: "service_provider_usage_created",
  SERVICE_PROVIDER_USAGE_UPDATED: "service_provider_usage_updated",
  SERVICE_PROVIDER_USAGE_DELETED: "service_provider_usage_deleted",
  TEMPLATE_CREATED: "template_created",
  TEMPLATE_ADDED_FROM_SYSTEM: "template_added_from_system",
  TEMPLATE_UPDATED: "template_updated",
  TEMPLATE_DELETED: "template_deleted",
  DOCUMENT_PUBLISHED: "document_published",
  DOCUMENT_PDF_DOWNLOADED: "document_pdf_downloaded",
  RECOMMENDATION_EXPANDED: "recommendation_expanded",
  TEAM_INVITATION_SENT: "team_invitation_sent",
  TEAM_INVITATION_CANCELED: "team_invitation_canceled",
  TEAM_MEMBER_ROLE_UPDATED: "team_member_role_updated",
  TEAM_MEMBER_REMOVED: "team_member_removed",
  ORGANIZATION_DELETED: "organization_deleted",
  INVITATION_ACCEPTED: "invitation_accepted",
  VOCABULARY_CODE_CREATED: "vocabulary_code_created",
  VOCABULARY_CODE_UPDATED: "vocabulary_code_updated",
  VOCABULARY_CODE_DELETED: "vocabulary_code_deleted",
} as const

export type PostHogEvent = (typeof POSTHOG_EVENTS)[keyof typeof POSTHOG_EVENTS]
