import { type Country } from "@plyco/shared"

export const requiredCodeSetIds = [
  "industries",
  "regions",
  "compliance_goals",
  "service_user_types",
  "service_customer_types",
  "privacy_supported_rights",
  "privacy_request_methods",
  "privacy_cookie_types",
  "privacy_cookie_consent_mechanisms",
  "privacy_cookie_consent_withdrawal_methods",
  "privacy_marketing_opt_out_methods",
  "privacy_transfer_mechanisms",
  "privacy_dpo_statuses",
  "privacy_eu_representative_statuses",
  "security_cadences",
  "security_penetration_testing_strategies",
  "security_encryption_algorithms",
  "security_tls_versions",
  "security_key_management_providers",
  "security_monitoring_modes",
  "security_notification_timelines",
  "security_customer_notification_processes",
  "data_categories",
  "subject_types",
  "data_purposes",
  "activity_role",
  "collection_methods",
  "legal_basis",
  "dpa_status",
  "vendor_criticality",
  "provider_categories",
  "data_processing_level",
  "provider_system_types",
  "activity_retention_policies",
  "defined_statuses",
] as const

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", active: true },
  { code: "AX", name: "Åland Islands", active: true },
  { code: "AL", name: "Albania", active: true },
  { code: "DZ", name: "Algeria", active: true },
  { code: "AS", name: "American Samoa", active: true },
  { code: "AD", name: "Andorra", active: true },
  { code: "AO", name: "Angola", active: true },
  { code: "AI", name: "Anguilla", active: true },
  { code: "AQ", name: "Antarctica", active: true },
  { code: "AG", name: "Antigua and Barbuda", active: true },
  { code: "AR", name: "Argentina", active: true },
  { code: "AM", name: "Armenia", active: true },
  { code: "AW", name: "Aruba", active: true },
  { code: "AU", name: "Australia", active: true },
  { code: "AT", name: "Austria", active: true },
  { code: "AZ", name: "Azerbaijan", active: true },
  { code: "BS", name: "Bahamas", active: true },
  { code: "BH", name: "Bahrain", active: true },
  { code: "BD", name: "Bangladesh", active: true },
  { code: "BB", name: "Barbados", active: true },
  { code: "BY", name: "Belarus", active: true },
  { code: "BE", name: "Belgium", active: true },
  { code: "BZ", name: "Belize", active: true },
  { code: "BJ", name: "Benin", active: true },
  { code: "BM", name: "Bermuda", active: true },
  { code: "BT", name: "Bhutan", active: true },
  { code: "BO", name: "Bolivia (Plurinational State of)", active: true },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", active: true },
  { code: "BA", name: "Bosnia and Herzegovina", active: true },
  { code: "BW", name: "Botswana", active: true },
  { code: "BV", name: "Bouvet Island", active: true },
  { code: "BR", name: "Brazil", active: true },
  { code: "IO", name: "British Indian Ocean Territory", active: true },
  { code: "BN", name: "Brunei Darussalam", active: true },
  { code: "BG", name: "Bulgaria", active: true },
  { code: "BF", name: "Burkina Faso", active: true },
  { code: "BI", name: "Burundi", active: true },
  { code: "CV", name: "Cabo Verde", active: true },
  { code: "KH", name: "Cambodia", active: true },
  { code: "CM", name: "Cameroon", active: true },
  { code: "CA", name: "Canada", active: true },
  { code: "KY", name: "Cayman Islands", active: true },
  { code: "CF", name: "Central African Republic", active: true },
  { code: "TD", name: "Chad", active: true },
  { code: "CL", name: "Chile", active: true },
  { code: "CN", name: "China", active: true },
  { code: "CX", name: "Christmas Island", active: true },
  { code: "CC", name: "Cocos (Keeling) Islands", active: true },
  { code: "CO", name: "Colombia", active: true },
  { code: "KM", name: "Comoros", active: true },
  { code: "CD", name: "Congo, Democratic Republic of the", active: true },
  { code: "CG", name: "Congo", active: true },
  { code: "CK", name: "Cook Islands", active: true },
  { code: "CR", name: "Costa Rica", active: true },
  { code: "CI", name: "Côte d'Ivoire", active: true },
  { code: "HR", name: "Croatia", active: true },
  { code: "CU", name: "Cuba", active: true },
  { code: "CW", name: "Curaçao", active: true },
  { code: "CY", name: "Cyprus", active: true },
  { code: "CZ", name: "Czechia", active: true },
  { code: "DK", name: "Denmark", active: true },
  { code: "DJ", name: "Djibouti", active: true },
  { code: "DM", name: "Dominica", active: true },
  { code: "DO", name: "Dominican Republic", active: true },
  { code: "EC", name: "Ecuador", active: true },
  { code: "EG", name: "Egypt", active: true },
  { code: "SV", name: "El Salvador", active: true },
  { code: "GQ", name: "Equatorial Guinea", active: true },
  { code: "ER", name: "Eritrea", active: true },
  { code: "EE", name: "Estonia", active: true },
  { code: "SZ", name: "Eswatini", active: true },
  { code: "ET", name: "Ethiopia", active: true },
  { code: "FK", name: "Falkland Islands (Malvinas)", active: true },
  { code: "FO", name: "Faroe Islands", active: true },
  { code: "FJ", name: "Fiji", active: true },
  { code: "FI", name: "Finland", active: true },
  { code: "FR", name: "France", active: true },
  { code: "GF", name: "French Guiana", active: true },
  { code: "PF", name: "French Polynesia", active: true },
  { code: "TF", name: "French Southern Territories", active: true },
  { code: "GA", name: "Gabon", active: true },
  { code: "GM", name: "Gambia", active: true },
  { code: "GE", name: "Georgia", active: true },
  { code: "DE", name: "Germany", active: true },
  { code: "GH", name: "Ghana", active: true },
  { code: "GI", name: "Gibraltar", active: true },
  { code: "GR", name: "Greece", active: true },
  { code: "GL", name: "Greenland", active: true },
  { code: "GD", name: "Grenada", active: true },
  { code: "GP", name: "Guadeloupe", active: true },
  { code: "GU", name: "Guam", active: true },
  { code: "GT", name: "Guatemala", active: true },
  { code: "GG", name: "Guernsey", active: true },
  { code: "GN", name: "Guinea", active: true },
  { code: "GW", name: "Guinea-Bissau", active: true },
  { code: "GY", name: "Guyana", active: true },
  { code: "HT", name: "Haiti", active: true },
  { code: "HM", name: "Heard Island and McDonald Islands", active: true },
  { code: "VA", name: "Holy See", active: true },
  { code: "HN", name: "Honduras", active: true },
  { code: "HK", name: "Hong Kong", active: true },
  { code: "HU", name: "Hungary", active: true },
  { code: "IS", name: "Iceland", active: true },
  { code: "IN", name: "India", active: true },
  { code: "ID", name: "Indonesia", active: true },
  { code: "IR", name: "Iran (Islamic Republic of)", active: true },
  { code: "IQ", name: "Iraq", active: true },
  { code: "IE", name: "Ireland", active: true },
  { code: "IM", name: "Isle of Man", active: true },
  { code: "IL", name: "Israel", active: true },
  { code: "IT", name: "Italy", active: true },
  { code: "JM", name: "Jamaica", active: true },
  { code: "JP", name: "Japan", active: true },
  { code: "JE", name: "Jersey", active: true },
  { code: "JO", name: "Jordan", active: true },
  { code: "KZ", name: "Kazakhstan", active: true },
  { code: "KE", name: "Kenya", active: true },
  { code: "KI", name: "Kiribati", active: true },
  { code: "KP", name: "Korea (Democratic People's Republic of)", active: true },
  { code: "KR", name: "Korea, Republic of", active: true },
  { code: "KW", name: "Kuwait", active: true },
  { code: "KG", name: "Kyrgyzstan", active: true },
  { code: "LA", name: "Lao People's Democratic Republic", active: true },
  { code: "LV", name: "Latvia", active: true },
  { code: "LB", name: "Lebanon", active: true },
  { code: "LS", name: "Lesotho", active: true },
  { code: "LR", name: "Liberia", active: true },
  { code: "LY", name: "Libya", active: true },
  { code: "LI", name: "Liechtenstein", active: true },
  { code: "LT", name: "Lithuania", active: true },
  { code: "LU", name: "Luxembourg", active: true },
  { code: "MO", name: "Macao", active: true },
  { code: "MG", name: "Madagascar", active: true },
  { code: "MW", name: "Malawi", active: true },
  { code: "MY", name: "Malaysia", active: true },
  { code: "MV", name: "Maldives", active: true },
  { code: "ML", name: "Mali", active: true },
  { code: "MT", name: "Malta", active: true },
  { code: "MH", name: "Marshall Islands", active: true },
  { code: "MQ", name: "Martinique", active: true },
  { code: "MR", name: "Mauritania", active: true },
  { code: "MU", name: "Mauritius", active: true },
  { code: "YT", name: "Mayotte", active: true },
  { code: "MX", name: "Mexico", active: true },
  { code: "FM", name: "Micronesia (Federated States of)", active: true },
  { code: "MD", name: "Moldova, Republic of", active: true },
  { code: "MC", name: "Monaco", active: true },
  { code: "MN", name: "Mongolia", active: true },
  { code: "ME", name: "Montenegro", active: true },
  { code: "MS", name: "Montserrat", active: true },
  { code: "MA", name: "Morocco", active: true },
  { code: "MZ", name: "Mozambique", active: true },
  { code: "MM", name: "Myanmar", active: true },
  { code: "NA", name: "Namibia", active: true },
  { code: "NR", name: "Nauru", active: true },
  { code: "NP", name: "Nepal", active: true },
  { code: "NL", name: "Netherlands", active: true },
  { code: "NC", name: "New Caledonia", active: true },
  { code: "NZ", name: "New Zealand", active: true },
  { code: "NI", name: "Nicaragua", active: true },
  { code: "NE", name: "Niger", active: true },
  { code: "NG", name: "Nigeria", active: true },
  { code: "NU", name: "Niue", active: true },
  { code: "NF", name: "Norfolk Island", active: true },
  { code: "MK", name: "North Macedonia", active: true },
  { code: "MP", name: "Northern Mariana Islands", active: true },
  { code: "NO", name: "Norway", active: true },
  { code: "OM", name: "Oman", active: true },
  { code: "PK", name: "Pakistan", active: true },
  { code: "PW", name: "Palau", active: true },
  { code: "PS", name: "Palestine, State of", active: true },
  { code: "PA", name: "Panama", active: true },
  { code: "PG", name: "Papua New Guinea", active: true },
  { code: "PY", name: "Paraguay", active: true },
  { code: "PE", name: "Peru", active: true },
  { code: "PH", name: "Philippines", active: true },
  { code: "PN", name: "Pitcairn", active: true },
  { code: "PL", name: "Poland", active: true },
  { code: "PT", name: "Portugal", active: true },
  { code: "PR", name: "Puerto Rico", active: true },
  { code: "QA", name: "Qatar", active: true },
  { code: "RE", name: "Réunion", active: true },
  { code: "RO", name: "Romania", active: true },
  { code: "RU", name: "Russian Federation", active: true },
  { code: "RW", name: "Rwanda", active: true },
  { code: "BL", name: "Saint Barthélemy", active: true },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", active: true },
  { code: "KN", name: "Saint Kitts and Nevis", active: true },
  { code: "LC", name: "Saint Lucia", active: true },
  { code: "MF", name: "Saint Martin (French part)", active: true },
  { code: "PM", name: "Saint Pierre and Miquelon", active: true },
  { code: "VC", name: "Saint Vincent and the Grenadines", active: true },
  { code: "WS", name: "Samoa", active: true },
  { code: "SM", name: "San Marino", active: true },
  { code: "ST", name: "Sao Tome and Principe", active: true },
  { code: "SA", name: "Saudi Arabia", active: true },
  { code: "SN", name: "Senegal", active: true },
  { code: "RS", name: "Serbia", active: true },
  { code: "SC", name: "Seychelles", active: true },
  { code: "SL", name: "Sierra Leone", active: true },
  { code: "SG", name: "Singapore", active: true },
  { code: "SX", name: "Sint Maarten (Dutch part)", active: true },
  { code: "SK", name: "Slovakia", active: true },
  { code: "SI", name: "Slovenia", active: true },
  { code: "SB", name: "Solomon Islands", active: true },
  { code: "SO", name: "Somalia", active: true },
  { code: "ZA", name: "South Africa", active: true },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", active: true },
  { code: "SS", name: "South Sudan", active: true },
  { code: "ES", name: "Spain", active: true },
  { code: "LK", name: "Sri Lanka", active: true },
  { code: "SD", name: "Sudan", active: true },
  { code: "SR", name: "Suriname", active: true },
  { code: "SJ", name: "Svalbard and Jan Mayen", active: true },
  { code: "SE", name: "Sweden", active: true },
  { code: "CH", name: "Switzerland", active: true },
  { code: "SY", name: "Syrian Arab Republic", active: true },
  { code: "TW", name: "Taiwan, Province of China", active: true },
  { code: "TJ", name: "Tajikistan", active: true },
  { code: "TZ", name: "Tanzania, United Republic of", active: true },
  { code: "TH", name: "Thailand", active: true },
  { code: "TL", name: "Timor-Leste", active: true },
  { code: "TG", name: "Togo", active: true },
  { code: "TK", name: "Tokelau", active: true },
  { code: "TO", name: "Tonga", active: true },
  { code: "TT", name: "Trinidad and Tobago", active: true },
  { code: "TN", name: "Tunisia", active: true },
  { code: "TR", name: "Türkiye", active: true },
  { code: "TM", name: "Turkmenistan", active: true },
  { code: "TC", name: "Turks and Caicos Islands", active: true },
  { code: "TV", name: "Tuvalu", active: true },
  { code: "UG", name: "Uganda", active: true },
  { code: "UA", name: "Ukraine", active: true },
  { code: "AE", name: "United Arab Emirates", active: true },
  { code: "GB", name: "United Kingdom", active: true },
  { code: "UM", name: "United States Minor Outlying Islands", active: true },
  { code: "US", name: "United States of America", active: true },
  { code: "UY", name: "Uruguay", active: true },
  { code: "UZ", name: "Uzbekistan", active: true },
  { code: "VU", name: "Vanuatu", active: true },
  { code: "VE", name: "Venezuela (Bolivarian Republic of)", active: true },
  { code: "VN", name: "Viet Nam", active: true },
  { code: "VG", name: "Virgin Islands (British)", active: true },
  { code: "VI", name: "Virgin Islands (U.S.)", active: true },
  { code: "WF", name: "Wallis and Futuna", active: true },
  { code: "EH", name: "Western Sahara", active: true },
  { code: "YE", name: "Yemen", active: true },
  { code: "ZM", name: "Zambia", active: true },
  { code: "ZW", name: "Zimbabwe", active: true },
]
