import { type Country, type VocabularyCodeSet } from "@complyflow/shared"

export const requiredCodeSetIds = [
  "industries",
  "regions",
  "compliance_goals",
  "data_categories",
  "subject_types",
  "data_purposes",
  "collection_methods",
  "legal_basis",
  "dpa_status",
  "vendor_criticality",
  "vendor_category",
  "data_processing_level",
  "provider_system_type",
] as const

export const countries: Country[] = [
  { code: "AU", name: "Australia", active: true },
  { code: "CA", name: "Canada", active: true },
  { code: "DE", name: "Germany", active: true },
  { code: "FR", name: "France", active: true },
  { code: "GB", name: "United Kingdom", active: true },
  { code: "IN", name: "India", active: true },
  { code: "NL", name: "Netherlands", active: true },
  { code: "SG", name: "Singapore", active: true },
  { code: "TH", name: "Thailand", active: true },
  { code: "US", name: "United States", active: true },
]

const codeSet = (
  codeSetId: string,
  name: string,
  isSystem: boolean,
  codes: Array<[string, string]>,
): VocabularyCodeSet => ({
  id: codeSetId,
  codeSetId,
  name,
  description: "",
  isSystem,
  codes: codes.map(([codeId, codeName], index) => ({
    id: `${codeSetId}:${codeId}`,
    codeId,
    name: codeName,
    sortOrder: index,
    active: true,
    isSystem,
  })),
})

export const defaultVocabularyCodeSets: VocabularyCodeSet[] = [
  codeSet("industries", "Industries", false, [
    ["artificial_intelligence", "Artificial Intelligence"],
    ["technology_saas", "Technology / SaaS"],
    ["healthcare", "Healthcare"],
    ["financial_services", "Financial Services"],
    ["edtech", "EdTech"],
    ["ecommerce", "E-commerce"],
    ["manufacturing", "Manufacturing"],
    ["professional_services", "Professional Services"],
  ]),
  codeSet("regions", "Regions", true, [
    ["us", "United States"],
    ["eu", "European Union"],
    ["uk", "United Kingdom"],
    ["apac", "Asia Pacific"],
    ["latam", "Latin America"],
    ["mea", "Middle East & Africa"],
    ["global", "Global"],
  ]),
  codeSet("compliance_goals", "Compliance Goals", false, [
    ["soc_2", "SOC 2"],
    ["gdpr", "GDPR"],
  ]),
  codeSet("data_categories", "Data categories", false, [
    ["account_data", "Account Data"],
    ["usage_data", "Usage Data"],
    ["billing_data", "Billing Data"],
    ["support_data", "Support Data"],
  ]),
  codeSet("subject_types", "Subject types", false, [
    ["administrator", "Administrator"],
    ["customer", "Customer"],
    ["end_user", "End User"],
    ["employee", "Employee"],
    ["contractor", "Contractor"],
    ["student", "Student"],
    ["website_visitor", "Website Visitor"],
  ]),
  codeSet("data_purposes", "Data purposes", false, [
    ["account_management", "Account Management"],
    ["billing_payments", "Billing and payments"],
    ["analytics", "Product analytics and improvement"],
    ["customer_support", "Customer support"],
    ["security", "Security, fraud prevention, and abuse detection"],
    ["legal_compliance", "Legal compliance"],
    ["marketing", "Marketing"],
    ["research", "Research"],
    ["service_delivery", "Service Delivery"],
    ["other", "Other"],
  ]),
  codeSet("collection_methods", "Collection methods", false, [
    ["account_signup", "Account signup"],
    ["product_usage", "Product usage"],
    ["manual_entry", "Manual entry"],
    ["customer_upload", "Customer upload"],
    ["integrations", "Integrations"],
    ["support_interaction", "Support interaction"],
    ["website_tracking", "Website tracking"],
  ]),
  codeSet("legal_basis", "Legal basis", false, [
    ["consent", "Consent"],
    ["contract", "Contract"],
    ["legal_obligation", "Legal obligation"],
    ["legitimate_interests", "Legitimate interests"],
  ]),
  codeSet("dpa_status", "DPA status", true, [
    ["not_required", "Not required"],
    ["not_started", "Not started"],
    ["requested", "Requested"],
    ["under_review", "Under review"],
    ["signed", "Signed"],
    ["unavailable", "Unavailable"],
    ["unknown", "Unknown"],
  ]),
  codeSet("vendor_criticality", "Vendor criticality", true, [
    ["low", "Low"],
    ["medium", "Medium"],
    ["high", "High"],
    ["critical", "Critical"],
  ]),
  codeSet("vendor_category", "Vendor category", false, [
    ["source_control", "Source control"],
    ["payments", "Payments"],
    ["project_management", "Project management"],
    ["provider", "Provider"],
  ]),
  codeSet("data_processing_level", "Data processing level", true, [
    ["none", "None"],
    ["limited", "Limited"],
    ["subprocessor", "Subprocessor"],
  ]),
  codeSet("provider_system_type", "Provider system type", true, [
    ["auth", "Auth"],
    ["source-control", "Source control"],
    ["cloud", "Cloud"],
    ["password-manager", "Password manager"],
  ]),
]
